In [1]:
import pandas as pd

In [18]:
ing_df = pd.read_csv('ingredients_master_list.csv', index_col="ingredient_name")
ing_df

,calories per gram,calories per cup,calories per piece
ingredient_name,,,
All-purpose flour,3.64,455,0
White rice (uncooked),3.60,685,0
Brown rice (uncooked),3.60,680,0
Rolled oats,3.79,300,0
Quinoa (uncooked),3.68,626,0
...,...,...,...
Chocolate chips (semi-sweet),4.80,804,0
Dark chocolate (70%),5.98,1016,170 (per bar)
Marshmallows,3.18,159,23 (per large)
Gelatin (powder),3.35,362,0
Coconut flakes (unsweetened),6.60,400,0

In [14]:
ing_df = pd.read_csv('ingredients_master_list.csv', index_col="ingredient_name")
ing_df = ing_df.drop(columns=['Unnamed: 0'])
ing_df.head()

                       calories per gram  calories per cup calories per piece
ingredient_name
All-purpose flour                   3.64               455                NaN
White rice (uncooked)               3.60               685                NaN
Brown rice (uncooked)               3.60               680                NaN
Rolled oats                         3.79               300                NaN
Quinoa (uncooked)                   3.68               626                NaN

In [3]:
ing_df.shape

(149, 4)

In [6]:
ing_df['calories per piece'].isnull

<bound method Series.isnull of 0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
            ...
144               NaN
145     170 (per bar)
146    23 (per large)
147               NaN
148               NaN
Name: calories per piece, Length: 149, dtype: object>

In [15]:
ing_df['calories per piece'] = ing_df['calories per piece'].fillna(0)

In [16]:
ing_df.head()

                       calories per gram  calories per cup calories per piece
ingredient_name
All-purpose flour                   3.64               455                  0
White rice (uncooked)               3.60               685                  0
Brown rice (uncooked)               3.60               680                  0
Rolled oats                         3.79               300                  0
Quinoa (uncooked)                   3.68               626                  0

In [17]:
ing_df.to_csv('ingredients_master_list.csv')

In [21]:
recipe_df = pd.read_csv('recipes_master_list.csv')
recipe_df.head()

,recipe_title,description,preparation_time,category,instruction,calories,protein,carbs,fats,"list of ingredients used (ingredient_name, quantity, unit, calories)"
0,Cheesy Bacon Omelet (Style #1),A classic hearty three-egg omelet loaded with ...,8 mins,breakfast,Step 1: Prep and clean all raw items. Step 2: ...,876,45g,119g,22g,(Large egg; 15; grams; 21 kcal) | (Bacon (raw)...
1,Classic BLT (Style #2),Crispy smoked bacon slices layered with fresh ...,13 mins,lunch,Step 1: Prep and clean all raw items. Step 2: ...,873,52g,102g,24g,(Bacon (raw); 100; grams; 417 kcal) | (Tomato;...
2,Classic Pork Chop Dinner (Style #3),"Thick, juicy boneless pork chops pan-seared al...",23 mins,dinner,Step 1: Prep and clean all raw items. Step 2: ...,1103,78g,115g,40g,"(Pork chop (raw, boneless); 30; grams; 30 kcal..."
3,Cottage Cheese with Berries (Style #4),High-protein cottage cheese topped with fresh ...,7 mins,snack,Step 1: Prep and clean all raw items. Step 2: ...,477,33g,52g,15g,(Cottage cheese; 150; grams; 147 kcal) | (Rasp...
4,Vanilla Berry Shortcake (Style #5),"Sweet, tender home-baked shortcake biscuits la...",25 mins,dessert,Step 1: Prep and clean all raw items. Step 2: ...,1320,70g,172g,43g,(All-purpose flour; 150; grams; 546 kcal) | (H...

In [25]:
recipe_df['list of ingredients used (ingredient_name, quantity, unit, calories)'][1]

'Step 1: Prep and clean all raw items. Step 2: Combine your base elements (Bacon (raw), Tomato). Step 3: Cook or assemble for 13 minutes. Step 4: Finish with remaining toppings and serve immediately.'

In [26]:
recipe_df['instruction'][1]

'Step 1: Prep and clean all raw items. Step 2: Combine your base elements (Bacon (raw), Tomato). Step 3: Cook or assemble for 13 minutes. Step 4: Finish with remaining toppings and serve immediately.'

In [24]:
recipe_df['preparation_time'].mac

<bound method Series.max of 0       8 mins
1      13 mins
2      23 mins
3       7 mins
4      25 mins
        ...
245     6 mins
246    18 mins
247    35 mins
248     8 mins
249    27 mins
Name: preparation_time, Length: 250, dtype: object>